# Introduction

## Terminology

- *Such as*: Classifications, thesauri, ontologies, subject authority files...
- *Known as:* Terminologies, Knowledge Organization Systems, Semantic Artefacts, Concept Schemes...
- *Core idea*: Things, not strings
- *Done with*: URIs, labels & links between

## JSKOS In a nutshell

- Encoding SKOS and related artefacts (concepts, mappings, concordances...) in JSON
- Knowledge graph data format with focus on knowledge organization systems
- Established infrastructure for controlled vocabularies at VZG
- Mature specification at <https://gbv.github.io/jskos/>

## Background and motivation

- Project **coli-conc** (2013-): infrastructure for (mappings between) knowledge organization systems
- **Cocoda** web application for mapping:
    - Design based on service-oriented architecture (SOA)
    - No server but everything (terminologies, mappings, accounts...) loosely coupled via APIs
    - â‡’ JSON
- Integration of federated data â‡’ RDF

## Influences and references

- **SKOS** for core classes and properties only
- **JSON-LD** for mapping to RDF
- Skosmos API and similar
- Wikibase Data Model
- [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/) for annotations
- [GeoJSON] for geospatial data
- [IIIF](https://iiif.io/api/presentation/3.0/) for media
- DCAT(-AP), vCard, XKOS, SSSOM...

## Some design guidelines

- Use exising standards (e.g. SKOS)
- Use URIs if possible
- Repeatable fields â‡”  arrays
- Standard first, implementation with tests and validation
- New features only with use case and data from practice

# Features of JSKOS

## Example: Concept (DDC)

~~~json
{
  "uri": "http://dewey.info/class/641/e23/",
  "type": [ { "uri": "http://www.w3.org/2004/02/skos/core#Concept" } ],
  "notation": [ "641" ],
  "prefLabel": {
    "en": "Food & drink",
    "de": "Essen und Trinken"
  }
}
~~~

## Example: Mapping (between DDC and Wikidata)

~~~json
{
  "type": ["http://www.w3.org/2004/02/skos/core#exactMatch"],
  "fromScheme": { "uri":"http://dewey.info/scheme/edition/e22/" },    
  "toScheme": { "uri": "http://bartoc.org/en/node/1940" },
  "from": {
    "memberSet": [ { "uri": "http://dewey.info/class/641/e22/" } ]
  },
  "to": {
    "memberSet": [ {
      "uri": "http://www.wikidata.org/entity/Q118451828"
      "prefLabel": { "en": "food and beverage" }
      } ]
  },
  "justification": "https://w3id.org/semapv/vocab/ManualMappingCuration",
  "tool": [ { "url": "https://coli-conc.gbv.de/cocoda/" } ]
}
~~~

## Concept bundles

Combination of concepts (e.g. early medieval cooking):

~~~json
{
  "uri": "http://dewey.info/class/641.50902/e23/",
  "notation": [ "641.50902" ],
  "memberList": [ {
    "uri": "http://dewey.info/class/641/e23/",
    "prefLabel": { "en": "Food & drink" }
  }, {
    "uri": "http://dewey.info/class/1--0902/e23/",
    "prefLabel": { "en": "6th to 12th century (500-1199)" }
  } ]
}
~~~

## Concept occurrences

~~~json
{
  "database": { "uri": "http://uri.gbv.de/database/opac-de-627" },
  "memberSet": [ {
    "uri": "http://dewey.info/class/641/e23/",
    "prefLabel": { "en": "Fodd & drink" }
   } ],
  "count": 607,
  "modified": "2025-11-17",
  "url": "https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHA&IKT=3011&NOABS=Y&TRM=641"
}
~~~

## JSKOS Object types

- Superclasses
  - **Item** (named entity) and **Resource** (anything)
  - **Concept bundles** âœ…
- **Concepts** âœ… and **Concept Schemes**
- **Mappings** âœ… and **Concordances**
- **Occurrences** âœ… of Concepts 
- **Registries**, **Distributions** and **Services** to collect and access
- **Annotations** to evaluate and comment

## Common fields of JSKOS items 

- Additional fields often found in knowledge organization:
  - previous/next, 
  - startDate/endDate
  - location, address, media...
  - identifier
  - version, versionOf
  - ...
- Metadata fields
  - creator, contributor, created, issued, modified
  - deprecated, tool...
- Fields linking JSKOS objects `inScheme`, `mappings`...
- ...TODO

## Closed world statements

- Missing field: *unknown*
- Empty array `[]`: *no value exists*
- `null` value in array (`[..., null]`): *more values exist*

## Qualified statements

- Inspired by Wikibase data model
- Arbitrary fields, identified by URIs (hello, RDF!)
- Optional ranking (preferred/normal/deprecated)
- Flexibility & extensibility at cost of full interoperability
- ...

TODO: example

# Applications of JSKOS

## Use cases

- [Cocoda](), [BARTOC](https://bartoc.org/), [DANTE](https://api.dante.gbv.de/)... at VZG 
- NFDI4Objects & TS4NFDI
- 2 or 3 implementations by third parties

## Applications & Libraries

- jskos-server: DBMS to store JSKOS data
- jskos-vue: widgets to nicely display JSKOS objects in browser (e.g. tree)
- jskos-proxy: serve and browse JSKOS data (terminologies) as Linked Open Data
- jskos-tools: helper functions for JSKOS data
- jskos-cli: tools to validate and convert JSKOS data
- ...

## JSKOS API

Not focus of this talk.

- GET/POST/PUT/PATCH data in JSKOS format
- Read & write endpoints for concepts, mappings...
- Multiple implementations (servers and clients)

# Comparisions

## Other knowledge graph formats

- RDF*
- Property graphs

## Why not JSON-LD?

- JSON-LD 1.0 released July 2012 to January 2014
- JSKOS 0.0.1 released in September 2014, prior work in 2013
- JSON-LD has limitations
- RDF was not our priority except for Linked Data principle 1: *Use URIs as names for things*

## JSON-LD has limitations

Common misunderstanding:

Parse JSON-LD with an RDF => syntax is secondary

RDF is just a secondary

- Use of JSON format without JSON Schema is limited

JSON-LD is

- ðŸ‘ writing RDF
- ðŸ‘ reading RDF
- ðŸ‘Ž well-defined key-value structure

## JSKOS is also JSON-LD

- JSKOS can be & is processed as JSON-LD with a non-normative \@context document to get RDF
- Some JSKOS fields require additional processing step or agreement on which property URIs to use


## End of opinion about JSON-LD

JSON-LD + JSON Schema => well-defined data usable both as plain JSON and as RDF graph

Example: repeatable fields are always arrays.

## When to use

...

## SOme limitations

- Labels MUST have language tag (use `und` for undefined)
- Notations don't have data types
- Some fields are about the concept (`uri`, `prefLabel`...),
  some about its metadata (`creator`, `modified`...), some about the conceptual entity
  (`startDate`, `location`...)
- Wikibase data model only covered partially
- Specification document is a one-man show

## Wish/idea

- JSKOS 0.7.0 being worked on (see issue tracker)
- Idea: specify a subset of JSKOS as official JSON(-LD) schema/context for SKOS
- Ongoing integration also beyond VZG

## Acknowledgements

...
